# Copyright 2026 Dora Lee

id = "mojom"
name = "Mojom"
version = "0.0.1"
schema_version = 1
authors = ["Dora Lee"]
description = "Mojom IDL language support for Zed."
repository = "https://github.com/dsa28s/zed-mojom-language"

[language_servers.mojom-lsp]
name = "Mojom Language Server"
languages = ["Mojom"]

[language_servers.mojom-lsp.language_ids]
"Mojom" = "mojom"

[grammars.mojom]
repository = "https://github.com/dsa28s/zed-mojom-language"
rev = "5cdb6b4e3a4b6dda354c4893ffc4447d6f3c742d"
path = "grammars/tree-sitter-mojom"
